### ISSUE TITLE
swagger文档中系统接口被elsa的接口文档覆盖了。

### ISSUE THREAD

**Issue by seamusic** [EasyAbp/Elsa#1]
swagger文档中系统接口被elsa的接口文档覆盖了，请问有好的解决办法吗？
![image](https://user-images.githubusercontent.com/172009/232850507-738f920d-e397-446e-a75d-beda106cf7bc.png)

**Comment by gdlcf88** [comment]
#2 could fix it.

However, I found more bugs while fixing it. I tried to fix them but failed. I am tired of this Elsa integration module and have no plans to continue fixing them for now.
